export const ActionTypes=
{   
    FETCH_PRODUCT:'FETCH_PRODUCT',
    FETCH_SELECTED_PRODUCT:'FETCH_SELECTED_PRODUCT',
    SET_PRODUCTS: 'SET_PRODUCTS',
    SELECTED_PRODUCT:'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCT:'REMOVE_SELECTED_PRODUCT',
    ADD_TO_CART:'ADD_TO_CART',
    DELETE_FROM_CART:'DELETE_FROM_CART',
    EMPTY_CART:'EMPTY_CART',
    
    
    
}